In [117]:
import numpy as np

In [118]:
import pandas as pd

In [119]:
import matplotlib.pyplot as plt

In [120]:
import seaborn as sns

In [121]:
df=pd.read_csv('D:\Machinelearning\dataset\mltrain.csv')

In [122]:
df.head(5)

Product_id  Stall_no             instock_date  Market_Category  \
0  BRAE2NF6JA5GUEXG      37.0  2015-08-22 18:36:12.000                2   
1  TUNE8SFB6RJN2HSD      38.0  2016-03-27 21:19:13.000               24   
2  BRAEAR7WZPQGPBZU       9.0  2015-08-18 19:25:22.000              447   
3  WATDZ2ZQ8JPDHCTJ      50.0  2016-03-28 21:53:01.000               23   
4  JWSEBUKYQPMBZ3RK       7.0  2016-03-29 22:58:53.000               63   

  Customer_name Loyalty_customer Product_Category  Grade  Demand  \
0      Lillyann              Yes          Fashion      1      68   
1         Klynn              Yes          Fashion      0      51   
2         Ridge              Yes       Child_care      0      10   
3         Abran              Yes      Educational      2      48   
4        Dustyn              Yes           Repair      1      35   

   Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  \
0             0.0      376.0           11.0         2983.0         4713.0   
1             0.0      397.0           12.0         7495.0        10352.0   
2             0.0      250.0            9.0         5752.0         7309.0   
3             0.0      144.0           13.0         5090.0        20814.0   
4             1.0      211.0            4.0         2430.0         9261.0   

   Selling_Price  
0    4185.947700  
1    9271.490256  
2    6785.701362  
3   13028.917824  
4     906.553935

In [124]:
df.drop(columns=['Product_id','instock_date','Customer_name','Loyalty_customer'],inplace=True)

In [125]:
df

Stall_no  Market_Category Product_Category  Grade  Demand  \
0         37.0                2          Fashion      1      68   
1         38.0               24          Fashion      0      51   
2          9.0              447       Child_care      0      10   
3         50.0               23      Educational      2      48   
4          7.0               63           Repair      1      35   
...        ...              ...              ...    ...     ...   
6363      17.0               24       Technology      0      47   
6364      21.0               55       Child_care      0      35   
6365      36.0              358           Repair      3      29   
6366      27.0              452           Repair      0       8   
6367      11.0               58       Technology      0      94   

      Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  \
0                0.0      376.0           11.0         2983.0         4713.0   
1                0.0      397.0           12.0         7495.0        10352.0   
2                0.0      250.0            9.0         5752.0         7309.0   
3                0.0      144.0           13.0         5090.0        20814.0   
4                1.0      211.0            4.0         2430.0         9261.0   
...              ...        ...            ...            ...            ...   
6363             0.0      614.0           10.0         8174.0        11266.0   
6364             0.0      269.0            5.0         3564.0         4920.0   
6365             0.0      283.0            3.0         5303.0        14614.0   
6366             0.0      267.0            3.0         4334.0         5849.0   
6367             0.0      614.0            7.0         3975.0         5383.0   

      Selling_Price  
0       4185.947700  
1       9271.490256  
2       6785.701362  
3      13028.917824  
4        906.553935  
...             ...  
6363   10277.520192  
6364    4501.837200  
6365   10218.878775  
6366    5359.493997  
6367    5220.013568  

[6368 rows x 11 columns]

In [126]:
df['Product_Category'].unique()

array(['Fashion', 'Child_care', 'Educational', 'Repair', 'Technology',
       'Cosmetics', 'Hospitality', 'Organic', 'Pet_care', 'Home_decor'],
      dtype=object)

In [130]:
product={'Product_Category':{'Fashion':1,'Child_care':2,'Educational':3,'Repair':3,'Technology':4,'Cosmetics':5,'Hospitality':6,'Organic':7,'Pet_care':8,'Home_decor':9}}

In [131]:
df.replace(product,inplace=True)

In [132]:
df.head(5)

Stall_no  Market_Category  Product_Category  Grade  Demand  Discount_avail  \
0      37.0                2                 1      1      68             0.0   
1      38.0               24                 1      0      51             0.0   
2       9.0              447                 2      0      10             0.0   
3      50.0               23                 3      2      48             0.0   
4       7.0               63                 3      1      35             1.0   

   charges_1  charges_2 (%)  Minimum_price  Maximum_price  Selling_Price  
0      376.0           11.0         2983.0         4713.0    4185.947700  
1      397.0           12.0         7495.0        10352.0    9271.490256  
2      250.0            9.0         5752.0         7309.0    6785.701362  
3      144.0           13.0         5090.0        20814.0   13028.917824  
4      211.0            4.0         2430.0         9261.0     906.553935

In [134]:
df['Selling_Price']=round(df['Selling_Price'],0)

In [135]:
df

Stall_no  Market_Category  Product_Category  Grade  Demand  \
0         37.0                2                 1      1      68   
1         38.0               24                 1      0      51   
2          9.0              447                 2      0      10   
3         50.0               23                 3      2      48   
4          7.0               63                 3      1      35   
...        ...              ...               ...    ...     ...   
6363      17.0               24                 4      0      47   
6364      21.0               55                 2      0      35   
6365      36.0              358                 3      3      29   
6366      27.0              452                 3      0       8   
6367      11.0               58                 4      0      94   

      Discount_avail  charges_1  charges_2 (%)  Minimum_price  Maximum_price  \
0                0.0      376.0           11.0         2983.0         4713.0   
1                0.0      397.0           12.0         7495.0        10352.0   
2                0.0      250.0            9.0         5752.0         7309.0   
3                0.0      144.0           13.0         5090.0        20814.0   
4                1.0      211.0            4.0         2430.0         9261.0   
...              ...        ...            ...            ...            ...   
6363             0.0      614.0           10.0         8174.0        11266.0   
6364             0.0      269.0            5.0         3564.0         4920.0   
6365             0.0      283.0            3.0         5303.0        14614.0   
6366             0.0      267.0            3.0         4334.0         5849.0   
6367             0.0      614.0            7.0         3975.0         5383.0   

      Selling_Price  
0            4186.0  
1            9271.0  
2            6786.0  
3           13029.0  
4             907.0  
...             ...  
6363        10278.0  
6364         4502.0  
6365        10219.0  
6366         5359.0  
6367         5220.0  

[6368 rows x 11 columns]

In [137]:
df['Stall_no'].isnull().sum()

5

In [142]:
df['Discount_avail'].isnull().sum()

38

In [144]:
df['charges_1'].isnull().sum()

198

In [146]:
df['charges_2 (%)'].isnull().sum()

205

In [148]:
df['Minimum_price'].isnull().sum()

38

In [149]:
df['Maximum_price'].isnull().sum()

343

In [151]:
df['Selling_Price'].isnull().sum()

41

In [155]:
m1=df['Stall_no'].median()

In [156]:
m1

25.0

In [157]:
df['Stall_no']=df['Stall_no'].fillna(m1)

In [158]:
df['Stall_no'].isnull().sum()

0

In [178]:
m2=df['Discount_avail'].median()

In [179]:
m2

0.0

In [180]:
df['Disocunt_avail']=df['Discount_avail'].fillna(m2)

In [181]:
df['Discount_avail'].isnull().sum()

38

In [164]:
m3=df['charges_1'].median()

In [165]:
m3

252.0

In [166]:
df['charges_1']=df['charges_1'].fillna(m3)

In [167]:
df['charges_1'].isnull().sum()

0

In [168]:
m4=df['charges_2 (%)'].median()

In [169]:
df['charges_2 (%)']=df['charges_2 (%)'].fillna(m4)

In [170]:
df['charges_2 (%)'].isnull().sum()

0

In [171]:
m5=df['Minimum_price'].median()

In [172]:
df['Minimum_price']=df['Minimum_price'].fillna(m5)

In [173]:
m6=df['Maximum_price'].median()

In [174]:
df['Maximum_price']=df['Maximum_price'].fillna(m6)

In [175]:
m7=df['Selling_Price'].median()

In [176]:
df['Selling_Price']=df['Selling_Price'].fillna(m7)

In [177]:
df.isnull().sum()

Stall_no             0
Market_Category      0
Product_Category     0
Grade                0
Demand               0
Discount_avail      38
charges_1            0
charges_2 (%)        0
Minimum_price        0
Maximum_price        0
Selling_Price        0
Disocunt_avail      38
dtype: int64

In [183]:
df.drop(columns=['Discount_avail'],inplace=True)

In [186]:
df.isnull().sum()

Stall_no            0
Market_Category     0
Product_Category    0
Grade               0
Demand              0
charges_1           0
charges_2 (%)       0
Minimum_price       0
Maximum_price       0
Selling_Price       0
Disocunt_avail      0
dtype: int64

In [187]:
df.head()

Stall_no  Market_Category  Product_Category  Grade  Demand  charges_1  \
0      37.0                2                 1      1      68      376.0   
1      38.0               24                 1      0      51      397.0   
2       9.0              447                 2      0      10      250.0   
3      50.0               23                 3      2      48      144.0   
4       7.0               63                 3      1      35      211.0   

   charges_2 (%)  Minimum_price  Maximum_price  Selling_Price  Disocunt_avail  
0           11.0         2983.0         4713.0         4186.0             0.0  
1           12.0         7495.0        10352.0         9271.0             0.0  
2            9.0         5752.0         7309.0         6786.0             0.0  
3           13.0         5090.0        20814.0        13029.0             0.0  
4            4.0         2430.0         9261.0          907.0             1.0

In [188]:
X=df.iloc[:,[0,1,2,3,4,5,6,7,8,10]].values

In [189]:
y=df.iloc[:,9].values

In [190]:
X

array([[3.7000e+01, 2.0000e+00, 1.0000e+00, ..., 2.9830e+03, 4.7130e+03,
        0.0000e+00],
       [3.8000e+01, 2.4000e+01, 1.0000e+00, ..., 7.4950e+03, 1.0352e+04,
        0.0000e+00],
       [9.0000e+00, 4.4700e+02, 2.0000e+00, ..., 5.7520e+03, 7.3090e+03,
        0.0000e+00],
       ...,
       [3.6000e+01, 3.5800e+02, 3.0000e+00, ..., 5.3030e+03, 1.4614e+04,
        0.0000e+00],
       [2.7000e+01, 4.5200e+02, 3.0000e+00, ..., 4.3340e+03, 5.8490e+03,
        0.0000e+00],
       [1.1000e+01, 5.8000e+01, 4.0000e+00, ..., 3.9750e+03, 5.3830e+03,
        0.0000e+00]])

In [191]:
y

array([ 4186.,  9271.,  6786., ..., 10219.,  5359.,  5220.])

In [192]:
from sklearn.model_selection import train_test_split

In [193]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [194]:
X_train

array([[1.9000e+01, 4.4300e+02, 4.0000e+00, ..., 3.4370e+03, 5.6340e+03,
        0.0000e+00],
       [2.9000e+01, 4.0300e+02, 3.0000e+00, ..., 1.7640e+03, 3.3320e+03,
        0.0000e+00],
       [1.5000e+01, 5.7000e+01, 7.0000e+00, ..., 1.9890e+03, 4.2710e+03,
        0.0000e+00],
       ...,
       [3.2000e+01, 2.3000e+01, 1.0000e+00, ..., 8.9600e+02, 3.9330e+03,
        0.0000e+00],
       [3.6000e+01, 1.9800e+02, 5.0000e+00, ..., 2.5220e+03, 3.2360e+03,
        0.0000e+00],
       [7.0000e+00, 1.3700e+02, 5.0000e+00, ..., 1.1347e+04, 1.4752e+04,
        1.0000e+00]])

In [195]:
X_test

array([[2.0000e+01, 5.8000e+01, 3.0000e+00, ..., 4.9720e+03, 6.6700e+03,
        0.0000e+00],
       [4.8000e+01, 2.6800e+02, 6.0000e+00, ..., 2.5360e+03, 4.6760e+03,
        0.0000e+00],
       [5.0000e+01, 3.0000e+01, 3.0000e+00, ..., 9.6200e+02, 4.0450e+03,
        0.0000e+00],
       ...,
       [1.2000e+01, 3.7000e+01, 3.0000e+00, ..., 7.4260e+03, 1.0131e+04,
        0.0000e+00],
       [3.1000e+01, 4.4800e+02, 8.0000e+00, ..., 5.0220e+03, 7.3660e+03,
        0.0000e+00],
       [2.4000e+01, 4.4700e+02, 3.0000e+00, ..., 3.1040e+03, 4.1420e+03,
        0.0000e+00]])

In [196]:
y_train

array([4617., 2742., 3162., ..., 2791., 3071., 1987.])

In [197]:
y_test

array([6084., 3837., 2594., ..., 8796., 6343., 3801.])

In [198]:
from sklearn.linear_model import LinearRegression

In [199]:
lr=LinearRegression()

In [200]:
lr.fit(X_train,y_train)

LinearRegression()

In [201]:
pred=lr.predict(X_test)

In [202]:
pred

array([5984.80574623, 4068.3977421 , 2762.04776811, ..., 8640.85180639,
       6168.21577914, 3975.16697491])

In [213]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(lr.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.88
